Repository jexia/jexia-sdk-js, pull requests merged in 2019-06, with the labels that each got.

#86 Add date/datetime dataset e2e test cases
  e2e/stories/select-record.e2e.ts
Labels: test

#90 Fix/init doc
  README.md
Labels: docs

#88 test(e2e): organize e2e tests
  e2e/lib/rtc.ts
  e2e/stories/dataset/create-record.e2e.ts
  e2e/stories/dataset/delete-record.e2e.ts
  e2e/stories/dataset/output-record.e2e.ts
  e2e/stories/dataset/select-record.e2e.ts
  e2e/stories/dataset/update-record.e2e.ts
  e2e/stories/jfs/jfs-delete.e2e.ts
  e2e/stories/jfs/jfs-select.e2e.ts
  e2e/stories/jfs/jfs-update.e2e.ts
  e2e/stories/jfs/jfs-upload.e2e.ts
  e2e/stories/rtc/rtc.e2e.ts
  e2e/stories/ums/ums.e2e.ts
  e2e/teardowns.ts
Labels: test

#95 refactor(tokenmanager): refactor tokenManager and improve test coverage
  src/api/core/tokenManager.spec.ts
  src/api/core/tokenManager.ts
Labels: test

#98 test(related): e2e tests for the related() method
  e2e/config.ts
  e2e/management.ts
  e2e/stories/relations/related.e2e.ts
  e2e/teardowns.ts
Labels: partial, test

#97 Add attach operation to datasets and filesets
  spec/filtering.ts
  spec/queryActionType.ts
  spec/testUtils.ts
  src/api/core/queries/actionQuery.spec.ts
  src/api/core/queries/actionQuery.ts
  src/api/core/queries/baseQuery.ts
  src/api/core/queries/filterableQuery.spec.ts
  src/api/core/queries/filterableQuery.ts
  src/api/dataops/dataset.spec.ts
  src/api/dataops/dataset.ts
  src/api/dataops/filteringApi.ts
  src/api/fileops/fileset.spec.ts
  src/api/fileops/fileset.ts
  src/internal/executer.interfaces.ts
  src/internal/executer.ts
  src/internal/query.spec.ts
  src/internal/query.ts
  src/internal/utils/index.ts
  src/internal/utils/queryActionType.ts
  src/internal/utils/queryParam.ts
Labels: partial

#100 Add detach operation to datasets and filesets
  src/api/core/queries/actionQuery.ts
  src/api/dataops/dataset.spec.ts
  src/api/dataops/dataset.ts
  src/api/fileops/fileset.spec.ts
  src/api/fileops/fileset.ts
  src/internal/utils/queryActionType.ts
Labels: partial

#103 ci(opencollective): disable opencollective on circleci
  .circleci/config.yml
Labels: build

#99 Documentation for the relations
  extra_docs/assets/relations-hints-1.png
  extra_docs/assets/relations-hints-2.png
  extra_docs/assets/relations-schema.png
  extra_docs/relations/README.md
  extra_docs/summary.json
Labels: docs

#101 Fix attach/detach make filter required and change method to PUT
  spec/queryAction.ts
  spec/requestMethod.ts
  spec/testUtils.ts
  src/api/core/queries/actionQuery.ts
  src/api/core/queries/baseQuery.spec.ts
  src/api/core/queries/baseQuery.ts
  src/api/core/queries/deleteQuery.spec.ts
  src/api/core/queries/deleteQuery.ts
  src/api/core/queries/filterableQuery.spec.ts
  src/api/core/queries/insertQuery.spec.ts
  src/api/core/queries/insertQuery.ts
  src/api/core/queries/selectQuery.ts
  src/api/core/queries/updateQuery.ts
  src/api/core/tokenManager.spec.ts
  src/api/core/tokenManager.ts
  src/api/dataops/dataset.spec.ts
  src/api/dataops/dataset.ts
  src/api/fileops/fileset.spec.ts
  src/api/fileops/fileset.ts
  src/api/ums/umsModule.spec.ts
  src/api/ums/umsModule.ts
  src/internal/executer.interfaces.ts
  src/internal/executer.spec.ts
  src/internal/executer.ts
  src/internal/requestAdapter.interfaces.ts
  src/internal/requestAdapter.spec.ts
  src/internal/requestAdapter.ts
Labels: bug

#102 Fix attach/detach parsing empty response
  spec/resource.ts
  spec/testUtils.ts
  src/api/core/queries/actionQuery.spec.ts
  src/api/core/queries/baseQuery.spec.ts
  src/api/core/queries/deleteQuery.spec.ts
  src/api/core/queries/filterableQuery.spec.ts
  src/api/core/queries/insertQuery.spec.ts
  src/api/core/queries/selectQuery.spec.ts
  src/api/core/queries/updateQuery.spec.ts
  src/internal/executer.spec.ts
  src/internal/requestAdapter.interfaces.ts
  src/internal/requestAdapter.spec.ts
  src/internal/requestAdapter.ts
Labels: bug

#106 build: add script to serve/watch docs
  package.json
Labels: build
