Repository jexia/jexia-sdk-js, pull requests merged in 2019-05, with the labels that each got.

#58 Allow single record object notation for inserting records
  extra_docs/quickstart.md
  src/api/dataops/dataset.spec.ts
  src/api/dataops/dataset.ts
Labels: enhancement

#60 task(module): add module configuration
  src/api/core/client.spec.ts
  src/api/core/client.ts
  src/api/core/module.ts
  src/api/dataops/dataOperationsModule.spec.ts
  src/api/dataops/dataOperationsModule.ts
  src/api/fileops/fileOperationsModule.ts
  src/api/fileops/fileops.interfaces.ts
  src/api/logger/loggerModule.spec.ts
  src/api/logger/loggerModule.ts
  src/api/realtime/realTimeModule.spec.ts
  src/api/realtime/realTimeModule.ts
  src/api/ums/umsModule.spec.ts
  src/api/ums/umsModule.ts
  src/browser.ts
  src/node.ts
Labels: partial

#61 Refactor BaseQuery and RequestExecutor
  package.json
  spec/queryAction.ts
  spec/testUtils.ts
  src/api/dataops/queries/baseQuery.spec.ts
  src/api/dataops/queries/baseQuery.ts
  src/api/dataops/queries/deleteQuery.spec.ts
  src/api/dataops/queries/insertQuery.spec.ts
  src/api/dataops/queries/insertQuery.ts
  src/api/dataops/queries/updateQuery.ts
  src/internal/executer.interfaces.ts
  src/internal/executer.spec.ts
  src/internal/executer.ts
  src/internal/query.spec.ts
  src/internal/query.ts
Labels: enhancement, partial

#63 Update dataset API to use query params
  src/api/dataops/queries/baseQuery.spec.ts
  src/api/dataops/queries/baseQuery.ts
  src/internal/executer.interfaces.ts
  src/internal/executer.spec.ts
  src/internal/executer.ts
  src/internal/query.spec.ts
  src/internal/query.ts
Labels: enhancement, partial

#68 Update filtering API
  src/api/dataops/filteringApi.spec.ts
  src/api/dataops/filteringApi.ts
  src/api/dataops/filteringCondition.spec.ts
  src/api/dataops/filteringCondition.ts
  src/internal/query.spec.ts
  src/internal/query.ts
  src/internal/utils.ts
Labels: enhancement, partial

#70 fix(request-executer): remove body from GET/DELETE requests
  src/internal/executer.spec.ts
  src/internal/executer.ts
Labels: bug

#80 Update e2e tests
  e2e/stories/delete-record.e2e.ts
  e2e/stories/output-record.e2e.ts
  e2e/stories/select-record.e2e.ts
Labels: test

#79 Validate e2e test env variables and update docs
  e2e/README.md
  package.json
  scripts/env-check.js
Labels: build, docs

#83 Add fileset unit tests
  extra_docs/jfs/README.md
  src/api/fileops/fileset.spec.ts
  src/api/fileops/fileset.ts
Labels: partial

#85 e2e tests for fileset CRUD
  e2e/stories/jfs-delete.e2e.ts
  e2e/stories/jfs-select.e2e.ts
  e2e/stories/jfs-update.e2e.ts
  e2e/stories/jfs-upload.e2e.ts
  e2e/teardowns.ts
Labels: partial, test

#87 Fileset CRUD operations
  e2e/stories/jfs-delete.e2e.ts
  e2e/stories/jfs-select.e2e.ts
  e2e/stories/jfs-update.e2e.ts
  e2e/stories/jfs-upload.e2e.ts
  e2e/teardowns.ts
  extra_docs/jfs/README.md
  extra_docs/quickstart.md
  spec/queryAction.ts
  spec/testUtils.ts
  src/api/core/queries/baseQuery.spec.ts
  src/api/core/queries/baseQuery.ts
  src/api/core/queries/deleteQuery.spec.ts
  src/api/core/queries/deleteQuery.ts
  src/api/core/queries/filterableQuery.spec.ts
  src/api/core/queries/filterableQuery.ts
  src/api/core/queries/insertQuery.spec.ts
  src/api/core/queries/insertQuery.ts
  src/api/core/queries/selectQuery.spec.ts
  src/api/core/queries/selectQuery.ts
  src/api/core/queries/updateQuery.spec.ts
  src/api/core/queries/updateQuery.ts
  src/api/dataops/dataset.spec.ts
  src/api/dataops/dataset.ts
  src/api/fileops/fileOperationsModule.ts
  src/api/fileops/fileset.spec.ts
  src/api/fileops/fileset.ts
  src/internal/executer.interfaces.ts
  src/internal/executer.spec.ts
  src/internal/executer.ts
  src/internal/query.spec.ts
  src/internal/query.ts
Labels: feature
