Repository jexia/jexia-sdk-js, pull requests merged in 2020-01, with the labels that each got.

#138 docs(relation): change examples to support rxjs requests
  extra_docs/relations/README.md
Labels: docs

#139 feat(ums): crud methods
  e2e/stories/ums/ums.e2e.ts
  package-lock.json
  package.json
  src/api/core/queries/filterableQuery.ts
  src/api/core/queries/insertQuery.spec.ts
  src/api/core/queries/insertQuery.ts
  src/api/core/queries/updateQuery.ts
  src/api/core/resource.ts
  src/api/dataops/dataset.ts
  src/api/ums/umsModule.spec.ts
  src/api/ums/umsModule.ts
  src/internal/executer.ts
Labels: partial

#140 test(ums): add ums crud e2e tests
  e2e/config.ts
  e2e/management.ts
  e2e/stories/ums/ums-crud.e2e.ts
  e2e/teardowns.ts
Labels: partial, test

#142 fix(browser): when calling global "process" an error is being thrown
  src/config/index.ts
Labels: bug

#141 docs(ums): ums crud operations documentation update
  extra_docs/ums/README.md
Labels: docs, partial
